/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttributeButton: typeof import('./src/components/AttributeButton.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    History: typeof import('./src/components/History.vue')['default']
    HistoryList: typeof import('./src/components/HistoryList.vue')['default']
    HitStatistics: typeof import('./src/components/HitStatistics.vue')['default']
    Omission: typeof import('./src/components/Omission.vue')['default']
    Select: typeof import('./src/components/Select.vue')['default']
    TrendChart: typeof import('./src/components/TrendChart.vue')['default']
  }
}
